encryptionsalt: v1:O3ix+WTW4qs=:v1:SO7IMnrxP8v9Vplc:JLHx+H9JY9/44Oema00M0P+qQjgl6A==
config:
  bedtime-infra:billingAccount:
    secure: v1:NAqiuuZkGlca70P7:dris7F2LEpTHfyS1N/B0Woa9VFWnCj3Ti5PnIlYM8eeARoka
  bedtime-infra:region: europe-west3
  bedtime-infra:githubRepo: ikushlianski/bedtime-stories
  gcp:project: bedtime-bootstrap
