import { eq, sql } from 'drizzle-orm'
import { db } from '@bedtime/core/db/client'
import {
  stories,
  annotations,
  feedback,
  runSnapshots,
  planQuestions,
  planConversations,
  parentReviews,
  childReactions,
  storyReadings,
  modelCalls,
  storyTextVersions,
  storyEmbeddings,
  storyUniverses,
  storyFragments,
  storyCharacters,
  storyWords,
  storyTopics,
  storyComments,
  modelSwapEvents,
  valueForMoneyFeedback,
  universeSuggestions,
  storyIllustrations,
  storyIllustrationMarkers,
} from '@bedtime/core/db/schema'

export async function deleteStoryCascade(storyId: number): Promise<void> {
  await db.batch([
    db.update(universeSuggestions).set({ sourceStoryId: null }).where(eq(universeSuggestions.sourceStoryId, storyId)),
    db.execute(sql`delete from character_memories where story_id = ${storyId}`),
    db.delete(annotations).where(eq(annotations.storyId, storyId)),
    db.delete(runSnapshots).where(eq(runSnapshots.storyId, storyId)),
    db.delete(feedback).where(eq(feedback.storyId, storyId)),
    db.delete(planQuestions).where(eq(planQuestions.storyId, storyId)),
    db.delete(planConversations).where(eq(planConversations.storyId, storyId)),
    db.delete(storyReadings).where(eq(storyReadings.storyId, storyId)),
    db.delete(modelCalls).where(eq(modelCalls.storyId, storyId)),
    db.delete(modelSwapEvents).where(eq(modelSwapEvents.storyId, storyId)),
    db.delete(valueForMoneyFeedback).where(eq(valueForMoneyFeedback.storyId, storyId)),
    db.delete(storyComments).where(eq(storyComments.storyId, storyId)),
    db.delete(parentReviews).where(eq(parentReviews.storyId, storyId)),
    db.delete(childReactions).where(eq(childReactions.storyId, storyId)),
    db.delete(storyFragments).where(eq(storyFragments.storyId, storyId)),
    db.delete(storyCharacters).where(eq(storyCharacters.storyId, storyId)),
    db.delete(storyWords).where(eq(storyWords.storyId, storyId)),
    db.delete(storyTopics).where(eq(storyTopics.storyId, storyId)),
    db.delete(storyTextVersions).where(eq(storyTextVersions.storyId, storyId)),
    db.delete(storyEmbeddings).where(eq(storyEmbeddings.storyId, storyId)),
    db.delete(storyUniverses).where(eq(storyUniverses.storyId, storyId)),
    db.delete(storyIllustrations).where(eq(storyIllustrations.storyId, storyId)),
    db.delete(storyIllustrationMarkers).where(eq(storyIllustrationMarkers.storyId, storyId)),
    db.delete(stories).where(eq(stories.id, storyId)),
  ])
}
